In [1]:
print("hi")

hi


In [2]:
initial = 100
ir=5
years=7
final = initial*(1+ir/100)**years
print(final)

140.71004226562505


In [3]:
initial == 100

True

In [4]:
initial ==200

False

In [5]:
print(initial)
initial = 200
print(initial)


100
200


In [6]:
initial = 100


In [7]:
name="My name is Teresa" #string
a=2 #integer
b=2. #float
c="2" #string
d=True #boolean

print(type(name))
print(type(a))
print(type(b))
print(type(c))
print(type(d))


<class 'str'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [9]:
v1=1/51*51
v2=1/49*49

print(v1)
print(v2)


1.0
0.9999999999999999


In [10]:
print(v1==1)
print(v2==1)


True
False


In [11]:
tol=1e-10
print(abs(v1-1)<tol)

True


In [ ]:
pi=3.1415926535
print(f"({pi:.3f}, {pi:.5})")
#this will print (3.142, 3.1416)
#the :.3f means print the float with 3 decimal places and the :.4 means print the float with 4 numbers (total)
#the f in front of the string means that it is a formatted string

(3.142, 3.1416)


In [7]:
large=10000000000
print(large)
print(f"A thousand times large is {large:g}")
#the command g will print the number in scientific notation if it is too large or too small

10000000000
A thousand times large is 1e+10


Now we are doing loops

In [8]:
initial=100
ir=5
years=7 
final=initial*(1+ir/100)**years


In [ ]:
for i in range(11): #the command range(11) creates a list of numbers from 0 to 10, it goes from 0 to N-1 in steps of 1
    final=initial*(1+ir/100)**i
    print(f"After {i} years, the final amount is {final:.2f}")
    #alternatively, one can creata a list startinf in a and ending in b with steps of s with the command range(a,b,s)

After 0 years, the final amount is 100.00
After 1 years, the final amount is 105.00
After 2 years, the final amount is 110.25
After 3 years, the final amount is 115.76
After 4 years, the final amount is 121.55
After 5 years, the final amount is 127.63
After 6 years, the final amount is 134.01
After 7 years, the final amount is 140.71
After 8 years, the final amount is 147.75
After 9 years, the final amount is 155.13
After 10 years, the final amount is 162.89


In [12]:
for m in range(3):
    for k in range(7): #This is a nested loop
        print(f"la multiplicación de {m} por {k} es igual a {m*k}")

la multiplicación de 0 por 0 es igual a 0
la multiplicación de 0 por 1 es igual a 0
la multiplicación de 0 por 2 es igual a 0
la multiplicación de 0 por 3 es igual a 0
la multiplicación de 0 por 4 es igual a 0
la multiplicación de 0 por 5 es igual a 0
la multiplicación de 0 por 6 es igual a 0
la multiplicación de 1 por 0 es igual a 0
la multiplicación de 1 por 1 es igual a 1
la multiplicación de 1 por 2 es igual a 2
la multiplicación de 1 por 3 es igual a 3
la multiplicación de 1 por 4 es igual a 4
la multiplicación de 1 por 5 es igual a 5
la multiplicación de 1 por 6 es igual a 6
la multiplicación de 2 por 0 es igual a 0
la multiplicación de 2 por 1 es igual a 2
la multiplicación de 2 por 2 es igual a 4
la multiplicación de 2 por 3 es igual a 6
la multiplicación de 2 por 4 es igual a 8
la multiplicación de 2 por 5 es igual a 10
la multiplicación de 2 por 6 es igual a 12


Write a loop that calculates the sum of all untergers from 1 to N and print the result

In [18]:
num=0
for i in range(11):
    num=num+i

print(num)

55


In [9]:
i=0
initial=100
ir=4
while i<11:
    final=initial*(1+ir/100)**i
    print(f"After {i} years, the final amount is {final:.2f}")
    i += 1 #this is the same as i=i+1 #update the value of i

print("done")

After 0 years, the final amount is 100.00
After 1 years, the final amount is 104.00
After 2 years, the final amount is 108.16
After 3 years, the final amount is 112.49
After 4 years, the final amount is 116.99
After 5 years, the final amount is 121.67
After 6 years, the final amount is 126.53
After 7 years, the final amount is 131.59
After 8 years, the final amount is 136.86
After 9 years, the final amount is 142.33
After 10 years, the final amount is 148.02
done


Write a loop that calculates the sum of all untergers from 1 to N and print the result using a WHILE loop


In [15]:
i=0
num=0
while i<11:
    num =num+i
    print(num)
    i += 1

0
1
3
6
10
15
21
28
36
45
55


CLASS 2

FUNCTIONS

In [ ]:
def final_amount(initial, years):
    """_summary_

    Args:
        initial (_type_): _description_
        years (_type_): _description_

    Returns:
        _type_: _description_
    """
    rate=5
    return initial*(1+rate/100)**years

In [2]:
final_amount(100,7)

140.71004226562505

In [10]:
def suma1aN(n):
    """_Funcion que suma todos los números de 1 hasta el N que le pongas_

    Args:
        N (interger):_numero hasta el que sumas_

    Returns:
        suma:_devuelve el valor de la suma_
    """
    suma=0
    for i in range(n+1):
        suma=suma+i
    return suma    

In [4]:
suma1aN(10)

55

Write a function that calculates the area and the circunference of a circle

In [11]:
from math import pi

In [14]:
def func_area_perimetro(r):
    """_summary_

    Args:
        r (float): El radio del circulo del que queremos calcular el área y el perímetro

    Returns:
        area, perimetro: Devuelve el área y el perímetro del círculo
    """
    area=2*pi*r
    perimetro=pi*r**2
    return area, perimetro


In [15]:
func_area_perimetro(1)


(6.283185307179586, 3.141592653589793)

not all functions have to return something

In [16]:
def silly(input):
    print(input)

In [17]:
silly("hi")

hi


In [18]:
def final_amount(initial, years, rate=5):
    return initial*(1+rate/100)**years

In [20]:
print(final_amount(100,7))
print(final_amount(100,7,6))

140.71004226562505
150.36302589913606


IF FUNCTIONS

In [22]:
def heaviside(x,a,b):
    f=0
    if a<=x<=b:
        f=1
    return f

In [23]:
heaviside(1,0,2)


1

EXERCISE

In [24]:
def interes(initial, years):
    if initial<=1000:
        return initial*(1+5/100)**years
    elif 1000<initial<=10000:
        return initial*(1+6/100)**years
    else:
        return initial*(1+8/100)**years


In [28]:
print(interes(200000, 7))
print(final_amount(200000,7,8))

342764.8537559042
342764.8537559042


LISTS

In [ ]:
lista=[1,2,3,"hola"]#listas pueden tener diferentes tipos de datos
print(lista)

[1, 2, 3, 'hola']


In [32]:
print(lista[0]) #lists start at 0, and to call an element of the list you use the command list[n] where n is the position of the element in the list
print(lista[1])
print(lista[2]) 
print(lista[3])
print(lista[-1]) #this will print the last element of the list
print(lista[-2]) #this will print the penultimate element of the list

1
2
3
hola
hola
3


In [33]:
len(lista) #this will give you the length of the list

4

In [39]:
empty=[ ]
len(empty) 

0

In [41]:
lista.append("lol") #this will add the element lol to the end of the list 

In [42]:
lista = lista + [4,5,6] #this will add the elements 4,5,6 to the end of the list
print(lista)

[1, 2, 3, 'hola', 'lol', 4, 5, 6]


In [43]:
del lista[0] #this will delete the first element of the list
print(lista)


[2, 3, 'hola', 'lol', 4, 5, 6]


EXERCISE

In [49]:
def listainteres(initial, years):
    interest=[]
    i=0
    for i in range(years+1):
        interest.append(initial*(1+5/100)**i)
        i+=1
    return interest  
    print(listainteres(100,10))

In [50]:
listainteres(100,10)

[100.0,
 105.0,
 110.25,
 115.76250000000002,
 121.55062500000003,
 127.62815625000003,
 134.00956406250003,
 140.71004226562505,
 147.7455443789063,
 155.13282159785163,
 162.8894626777442]

In [52]:
a=5.3
if a<5:
    print("hola")
elif a>5:
    print("adios")
elif a==5:
    print("chao")
    

adios


lists are linked, so if L1=L2 and you change things from L1 they will be changed from L1 also. For this to not happen, we do L1=.copyL2

There can also be lists inside of lists, its just one more element of the list

In [56]:
lista1=[0,1,2,3,4,5,6,7,8,9,10]
print(lista1)
print(lista1[0: len(lista1):2]) #we can print some elements of a list like list[a:b:s] where a is the first element we want to print, b is the last element we want to print and s is the step

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 2, 4, 6, 8, 10]


CLASS 3: NUMPY

We are going to use some python libraries (they are very usefull when coding)

In [1]:
#The first lines of your code should import all the libraries and functions you are using throughout your code
import os #this is a library that allows you to interact with the operating system
import scipy
import numpy as np #this way, when you want to call a function from numpy, you can just write np.function instead of numpy.function
import matplotlib.pyplot as plt 


In [2]:
root=np.sqrt(2)
print(root)

1.4142135623730951


creating numpy array

In [3]:
vec=np.array([1,2,3])
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])

In [4]:
print(vec.shape)
print(A.shape)
print(B.shape)

(3,)
(3, 3)
(2, 3, 2)


In [5]:
print(vec)
print(A)
print(B)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [6]:
print(vec.size)
print(A.size)
print(B.size)


3
9
12


In [7]:
print(np.shape(A))


(3, 3)


In [8]:
A.dtype

dtype('int64')

In [9]:
M2=np.array([[1,2],[3,4]], dtype=complex)

generating functions: functions that generate arrays

In [10]:
v=np.arange(0,10,1) #this will create a list of numbers from 0 to 9 in steps of 1
print(v)

V=np.arange(-1,1,0.1)
print(V)

[0 1 2 3 4 5 6 7 8 9]
[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


In [11]:
v=np.linspace(0,10,11) #this will create a list of numbers from 0 to 10 with 11 elements
print(v)

v=np.linspace(-1,1,21)
print(v)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[-1.  -0.9 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3
  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


In [12]:
Z1=np.zeros(2, dtype=int)
Z2=np.zeros((3,3))
Z3=np.zeros((2,3,3))
print(Z1)
print(Z2)
print(Z3)
            

[0 0]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [13]:
Identity=np.eye(4)#this will create a 4x4 identity matrix
Diagonal=np.diag([1,2,3,4])#this will create a diagonal matrix with the elements of the list
Random=np.random.rand(5,5)#this will create a 5x5 matrix with random numbers between 0 and 1
print(Identity)
print(Diagonal)
print(Random)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0.59332966 0.21162032 0.31327299 0.23495071 0.63601072]
 [0.52160932 0.26936611 0.57610859 0.89905231 0.33424389]
 [0.30467665 0.42667421 0.0573176  0.4980007  0.73189251]
 [0.56556119 0.73028429 0.47641666 0.99398525 0.02789327]
 [0.98733755 0.72106926 0.09127399 0.09721317 0.74129251]]


In [29]:
print(Identity[-1])
print(Identity[1:1])

[0. 0. 0. 1.]
[]
