In [2]:
print("hi")

hi


In [3]:
initial = 100
ir=5
years=7
final = initial*(1+ir/100)**years
print(final)

140.71004226562505


In [4]:
initial == 100

True

In [5]:
initial ==200

False

In [6]:
print(initial)
initial = 200
print(initial)


100
200


In [7]:
initial = 100


In [8]:
name="My name is Teresa" #string
a=2 #integer
b=2. #float
c="2" #string
d=True #boolean

print(type(name))
print(type(a))
print(type(b))
print(type(c))
print(type(d))


<class 'str'>
<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [9]:
v1=1/51*51
v2=1/49*49

print(v1)
print(v2)


1.0
0.9999999999999999


In [10]:
print(v1==1)
print(v2==1)


True
False


In [11]:
tol=1e-10
print(abs(v1-1)<tol)

True


In [12]:
pi=3.1415926535
print(f"({pi:.3f}, {pi:.5})")
#this will print (3.142, 3.1416)
#the :.3f means print the float with 3 decimal places and the :.4 means print the float with 4 numbers (total)
#the f in front of the string means that it is a formatted string

(3.142, 3.1416)


In [13]:
large=10000000000
print(large)
print(f"A thousand times large is {large:g}")
#the command g will print the number in scientific notation if it is too large or too small

10000000000
A thousand times large is 1e+10


Now we are doing loops

In [14]:
initial=100
ir=5
years=7 
final=initial*(1+ir/100)**years


In [15]:
for i in range(11): #the command range(11) creates a list of numbers from 0 to 10, it goes from 0 to N-1 in steps of 1
    final=initial*(1+ir/100)**i
    print(f"After {i} years, the final amount is {final:.2f}")
    #alternatively, one can creata a list startinf in a and ending in b with steps of s with the command range(a,b,s)

After 0 years, the final amount is 100.00
After 1 years, the final amount is 105.00
After 2 years, the final amount is 110.25
After 3 years, the final amount is 115.76
After 4 years, the final amount is 121.55
After 5 years, the final amount is 127.63
After 6 years, the final amount is 134.01
After 7 years, the final amount is 140.71
After 8 years, the final amount is 147.75
After 9 years, the final amount is 155.13
After 10 years, the final amount is 162.89


In [16]:
for m in range(3):
    for k in range(7): #This is a nested loop
        print(f"la multiplicación de {m} por {k} es igual a {m*k}")

la multiplicación de 0 por 0 es igual a 0
la multiplicación de 0 por 1 es igual a 0
la multiplicación de 0 por 2 es igual a 0
la multiplicación de 0 por 3 es igual a 0
la multiplicación de 0 por 4 es igual a 0
la multiplicación de 0 por 5 es igual a 0
la multiplicación de 0 por 6 es igual a 0
la multiplicación de 1 por 0 es igual a 0
la multiplicación de 1 por 1 es igual a 1
la multiplicación de 1 por 2 es igual a 2
la multiplicación de 1 por 3 es igual a 3
la multiplicación de 1 por 4 es igual a 4
la multiplicación de 1 por 5 es igual a 5
la multiplicación de 1 por 6 es igual a 6
la multiplicación de 2 por 0 es igual a 0
la multiplicación de 2 por 1 es igual a 2
la multiplicación de 2 por 2 es igual a 4
la multiplicación de 2 por 3 es igual a 6
la multiplicación de 2 por 4 es igual a 8
la multiplicación de 2 por 5 es igual a 10
la multiplicación de 2 por 6 es igual a 12


Write a loop that calculates the sum of all untergers from 1 to N and print the result

In [17]:
num=0
for i in range(11):
    num=num+i

print(num)

55


In [18]:
i=0
initial=100
ir=4
while i<11:
    final=initial*(1+ir/100)**i
    print(f"After {i} years, the final amount is {final:.2f}")
    i += 1 #this is the same as i=i+1 #update the value of i

print("done")

After 0 years, the final amount is 100.00
After 1 years, the final amount is 104.00
After 2 years, the final amount is 108.16
After 3 years, the final amount is 112.49
After 4 years, the final amount is 116.99
After 5 years, the final amount is 121.67
After 6 years, the final amount is 126.53
After 7 years, the final amount is 131.59
After 8 years, the final amount is 136.86
After 9 years, the final amount is 142.33
After 10 years, the final amount is 148.02
done


Write a loop that calculates the sum of all untergers from 1 to N and print the result using a WHILE loop


In [19]:
i=0
num=0
while i<11:
    num =num+i
    print(num)
    i += 1

0
1
3
6
10
15
21
28
36
45
55


CLASS 2

FUNCTIONS

In [20]:
def final_amount(initial, years):
    """_summary_

    Args:
        initial (_type_): _description_
        years (_type_): _description_

    Returns:
        _type_: _description_
    """
    rate=5
    return initial*(1+rate/100)**years

In [21]:
final_amount(100,7)

140.71004226562505

In [22]:
def suma1aN(n):
    """_Funcion que suma todos los números de 1 hasta el N que le pongas_

    Args:
        N (interger):_numero hasta el que sumas_

    Returns:
        suma:_devuelve el valor de la suma_
    """
    suma=0
    for i in range(n+1):
        suma=suma+i
    return suma    

In [23]:
suma1aN(10)

55

Write a function that calculates the area and the circunference of a circle

In [24]:
from math import pi

In [25]:
def func_area_perimetro(r):
    """_summary_

    Args:
        r (float): El radio del circulo del que queremos calcular el área y el perímetro

    Returns:
        area, perimetro: Devuelve el área y el perímetro del círculo
    """
    area=2*pi*r
    perimetro=pi*r**2
    return area, perimetro


In [26]:
func_area_perimetro(1)


(6.283185307179586, 3.141592653589793)

not all functions have to return something

In [27]:
def silly(input):
    print(input)

In [28]:
silly("hi")

hi


In [29]:
def final_amount(initial, years, rate=5):
    return initial*(1+rate/100)**years

In [30]:
print(final_amount(100,7))
print(final_amount(100,7,6))

140.71004226562505
150.36302589913606


IF FUNCTIONS

In [31]:
def heaviside(x,a,b):
    f=0
    if a<=x<=b:
        f=1
    return f

In [32]:
heaviside(1,0,2)


1

EXERCISE

In [33]:
def interes(initial, years):
    if initial<=1000:
        return initial*(1+5/100)**years
    elif 1000<initial<=10000:
        return initial*(1+6/100)**years
    else:
        return initial*(1+8/100)**years


In [34]:
print(interes(200000, 7))
print(final_amount(200000,7,8))

342764.8537559042
342764.8537559042


LISTS

In [35]:
lista=[1,2,3,"hola"]#listas pueden tener diferentes tipos de datos
print(lista)

[1, 2, 3, 'hola']


In [36]:
print(lista[0]) #lists start at 0, and to call an element of the list you use the command list[n] where n is the position of the element in the list
print(lista[1])
print(lista[2]) 
print(lista[3])
print(lista[-1]) #this will print the last element of the list
print(lista[-2]) #this will print the penultimate element of the list

1
2
3
hola
hola
3


In [37]:
len(lista) #this will give you the length of the list

4

In [38]:
empty=[ ]
len(empty) 

0

In [39]:
lista.append("lol") #this will add the element lol to the end of the list 

In [40]:
lista = lista + [4,5,6] #this will add the elements 4,5,6 to the end of the list
print(lista)

[1, 2, 3, 'hola', 'lol', 4, 5, 6]


In [41]:
del lista[0] #this will delete the first element of the list
print(lista)


[2, 3, 'hola', 'lol', 4, 5, 6]


EXERCISE

In [42]:
def listainteres(initial, years):
    interest=[]
    i=0
    for i in range(years+1):
        interest.append(initial*(1+5/100)**i)
        i+=1
    return interest  
    print(listainteres(100,10))

In [43]:
listainteres(100,10)

[100.0,
 105.0,
 110.25,
 115.76250000000002,
 121.55062500000003,
 127.62815625000003,
 134.00956406250003,
 140.71004226562505,
 147.7455443789063,
 155.13282159785163,
 162.8894626777442]

In [44]:
a=5.3
if a<5:
    print("hola")
elif a>5:
    print("adios")
elif a==5:
    print("chao")
    

adios


lists are linked, so if L1=L2 and you change things from L1 they will be changed from L1 also. For this to not happen, we do L1=.copyL2

There can also be lists inside of lists, its just one more element of the list

In [45]:
lista1=[0,1,2,3,4,5,6,7,8,9,10]
print(lista1)
print(lista1[0: len(lista1):2]) #we can print some elements of a list like list[a:b:s] where a is the first element we want to print, b is the last element we want to print and s is the step

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 2, 4, 6, 8, 10]


CLASS 3: NUMPY

We are going to use some python libraries (they are very usefull when coding)

In [46]:
#The first lines of your code should import all the libraries and functions you are using throughout your code
import os #this is a library that allows you to interact with the operating system
import scipy
import numpy as np #this way, when you want to call a function from numpy, you can just write np.function instead of numpy.function
import matplotlib.pyplot as plt 


In [47]:
root=np.sqrt(2)
print(root)

1.4142135623730951


creating numpy array

In [48]:
vec=np.array([1,2,3])
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])

In [49]:
print(vec.shape)
print(A.shape)
print(B.shape)

(3,)
(3, 3)
(2, 3, 2)


In [50]:
print(vec)
print(A)
print(B)

[1 2 3]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [51]:
print(vec.size)
print(A.size)
print(B.size)


3
9
12


In [52]:
print(np.shape(A))


(3, 3)


In [53]:
A.dtype

dtype('int64')

In [54]:
M2=np.array([[1,2],[3,4]], dtype=complex)

generating functions: functions that generate arrays

In [55]:
v=np.arange(0,10,1) #this will create a list of numbers from 0 to 9 in steps of 1
print(v)

V=np.arange(-1,1,0.1)
print(V)

[0 1 2 3 4 5 6 7 8 9]
[-1.00000000e+00 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01
 -6.00000000e-01 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01
 -2.00000000e-01 -1.00000000e-01 -2.22044605e-16  1.00000000e-01
  2.00000000e-01  3.00000000e-01  4.00000000e-01  5.00000000e-01
  6.00000000e-01  7.00000000e-01  8.00000000e-01  9.00000000e-01]


In [56]:
v=np.linspace(0,10,11) #this will create a list of numbers from 0 to 10 with 11 elements
print(v)

v=np.linspace(-1,1,21)
print(v)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[-1.  -0.9 -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3
  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


In [57]:
Z1=np.zeros(2, dtype=int)
Z2=np.zeros((3,3))
Z3=np.zeros((2,3,3))
print(Z1)
print(Z2)
print(Z3)
            

[0 0]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [58]:
Identity=np.eye(4)#this will create a 4x4 identity matrix
Diagonal=np.diag([1,2,3,4])#this will create a diagonal matrix with the elements of the list
Random=np.random.rand(5,5)#this will create a 5x5 matrix with random numbers between 0 and 1
print(Identity)
print(Diagonal)
print(Random)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
[[0.06411016 0.71136347 0.87071141 0.56458858 0.73944912]
 [0.99100438 0.2910473  0.33522561 0.56061501 0.03424099]
 [0.62269615 0.26970483 0.37631835 0.25524772 0.08699995]
 [0.63879659 0.50220117 0.5194679  0.85267209 0.11977006]
 [0.83892082 0.23697017 0.55371885 0.07165139 0.89148938]]


In [59]:
print(Identity[-1])
print(Identity[1:])

[0. 0. 0. 1.]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


LAST FILIPA CLASS

In [60]:
seno=np.array([])
x=0
while 0<=x<=2*np.pi:
    seno=np.append(seno, np.sin(x))
    x=x+0.01

print(seno)
print(x)

[ 0.          0.00999983  0.01999867  0.0299955   0.03998933  0.04997917
  0.05996401  0.06994285  0.07991469  0.08987855  0.09983342  0.1097783
  0.11971221  0.12963414  0.13954311  0.14943813  0.15931821  0.16918235
  0.17902957  0.18885889  0.19866933  0.2084599   0.21822962  0.22797752
  0.23770263  0.24740396  0.25708055  0.26673144  0.27635565  0.28595223
  0.29552021  0.30505864  0.31456656  0.32404303  0.33348709  0.34289781
  0.35227423  0.36161543  0.37092047  0.38018842  0.38941834  0.39860933
  0.40776045  0.4168708   0.42593947  0.43496553  0.44394811  0.45288629
  0.46177918  0.47062589  0.47942554  0.48817725  0.49688014  0.50553334
  0.51413599  0.52268723  0.5311862   0.53963205  0.54802394  0.55636102
  0.56464247  0.57286746  0.58103516  0.58914476  0.59719544  0.60518641
  0.61311685  0.62098599  0.62879302  0.63653718  0.64421769  0.65183377
  0.65938467  0.66686964  0.67428791  0.68163876  0.68892145  0.69613524
  0.70327942  0.71035327  0.71735609  0.72428717  0.

In [61]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


If we use * for the multiplication of vectors it will do the multiplication of the elements
If we use @ it will do the normal multiplication.

For the alter product we can use np.outer
And there's many more things in numpy thet we can use

In [89]:
Z=np.array([[2,3,2,4],[4,1,0,17],[24,0,-1,-3],[4,2,14,2]])
H=np.zeros((4,4), dtype=int)
A=np.zeros((2,2), dtype=complex)
X=np.zeros((2,2))
print(Z)
i=0
k=0
for i in range(4):
    for k in range(4):
        if i==k or i==0 and k==3 or i==3 and k==0:
            H[i,k]=Z[i,k]
            k=k+1
        else:
            H[i,k]=0
            k=k+1
        
    i=i+1
print(H)


Z=np.delete(Z,[1,2],0)
Z=np.delete(Z,[1,2],1)
X=Z
print(X)

i=0
k=0
for i in range(2):
    for k in range(2):
        A[i,k]=np.round(np.exp(-1j * np.pi * X[i,k]), decimals=10)
        k=k+1
    i=i+1

print(A)
                     

[[ 2  3  2  4]
 [ 4  1  0 17]
 [24  0 -1 -3]
 [ 4  2 14  2]]
[[ 2  0  0  4]
 [ 0  1  0  0]
 [ 0  0 -1  0]
 [ 4  0  0  2]]
[[2 4]
 [4 2]]
[[1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j]]


FOLDERS, AND FILES IN GENERAL


In [90]:
#We can create a path to a file with the os command

path= "/c/Users/Teresa/Desktop/COMPU/Clases_Filipa/Clases_Filipa/"
folder= "Data/"
#We can save it to that path

In [91]:
x=np.linspace(0,10,11) 
y=np.sin(2*np.pi*x)
print(y)

[ 0.00000000e+00 -2.44929360e-16 -4.89858720e-16 -7.34788079e-16
 -9.79717439e-16 -1.22464680e-15 -1.46957616e-15 -1.71450552e-15
 -1.95943488e-15 -2.20436424e-15 -2.44929360e-15]


In [93]:
np.save(os.path.join(path,"sine"),x)
#This saves the file in the path we created with the name sine.npy

FileNotFoundError: [Errno 2] No such file or directory: '/c/Users/Teresa/Desktop/COMPU/Clases_Filipa/Clases_Filipa/sine.npy'