# SUMMARY OF IMPORTANT CODE


## LOOPS

In [1]:
x=0
for i in range(5):
    x=x+1
    print(x)
    i=i+1

1
2
3
4
5


In [1]:
i=0
while i<5:
    print("Esto se repite", i, "veces")
    i+=1

Esto se repite 0 veces
Esto se repite 1 veces
Esto se repite 2 veces
Esto se repite 3 veces
Esto se repite 4 veces


## BOOLEAN LOGIC


In [4]:
a = 0
b = 1.2
print(a >= 0 and b < 1)
print(a >= 0 or b < 1)
print(a > 0 or b > 1)
print(a > 0 or not b > 1)
print(-1 < a <= 0)
print(not (a > 0 or b > 0))

False
True
True
False
True
False


## FUNCTIONS

def function_name(argument_1, argument_2):
    local_variable_1 = value_1
    local_variable_2 = value_2
    return expression

In [5]:
def funcion_raiz(x, n):
    """_RAIZ_

    Args:
        x (float): number to make the root of
        n (int): value of the root

    Returns:
        float: nth root of x
    """
    return x**(1/n)

funcion_raiz(27, 3)

3.0

## IF STATEMENTS

In [ ]:
def heaviside1(x,a,b):
    f=False
    if a <= x <= b:    #This way you use onlu one if
        f=True
    return f

print(heaviside1(0,10,20))
print(heaviside1(11, 10, 20))


False
True


We can also make elif statements and else statements that work the same way the if statement works.

## LISTS

In [20]:
lista1=[1,2,3,"hola"]
lista1.append(4)    #Add an element at the end of the list
print(lista1[2])    #Print the third element of the list
len(lista1)    #Print the length of the list
print(lista1)
print(lista1[:3])   #Print the first three elements of the list
print(lista1[1:3])  #Print the second and third elements of the list
print(lista1[:])   


3
[1, 2, 3, 'hola', 4]
[1, 2, 3]
[2, 3]
[1, 2, 3, 'hola', 4]


In [21]:
empty=[]
len(empty)

0

In [22]:
lista1=lista1+[5,6,7]    #Add elements to the list
print(lista1)   
del lista1[3]    #Delete the fourth element of the list
print(lista1)

[1, 2, 3, 'hola', 4, 5, 6, 7]
[1, 2, 3, 4, 5, 6, 7]


In [23]:
nest=[lista1, [1,2,3], [4,5,6]]
print(nest)
nest[0][3]    #Print the fourth element of the first list



[[1, 2, 3, 4, 5, 6, 7], [1, 2, 3], [4, 5, 6]]


4

## PHYTHON LIBRARIES: NUMPY

In [27]:
import numpy as np  # This way of importing prevents us from typing `numpy` every time. Instead, we can just type `np`
import scipy

numpy has some functions made already that can help the code 

In [28]:
A = np.array([[1,2,3], [4,5,6], [7, 8, 9]]) # A 3x3 matrix, an array of only numbers
print(type(A)) #type of the variable
print(np.shape(A)) #shape of the matrix
print(np.size(A)) #number of elements in the matrix
M2 = np.array([[1, 2], [3j, 4]], dtype=complex)
print(M2)



<class 'numpy.ndarray'>
(3, 3)
9
[[1.+0.j 2.+0.j]
 [0.+3.j 4.+0.j]]


In [29]:
v = np.arange(0,10,0.5) #Create an array from 0 to 10-0.5 with a step of 0.5
print(v)
u= np.linspace(0, 10, 21) #crates an array from 0 to 10 with 21 elements (now 10 is included)
print(u)


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [30]:
z=np.zeros((3,3)) #creates a 3x3 matrix with zeros
o=np.ones((3,2)) #creates a 3x2 matrix with ones
I=np.eye(4)  # Creates a 4x4 identity matrix.
D=np.diag([1,2,3])  # Creates a matrix with the input list in the diagonal
R=np.random.rand(5, 5)  # Creates a 5x5 matrix with random entries between 0 and 1
print(z)
print(o)
print(I)
print(D)
print(R)
print(R[2,3])
print(R[-1:])
print(R[1:3]) #Prints the second and third rows



[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0.48130662 0.01445967 0.53822399 0.80115397 0.67627912]
 [0.25958537 0.49856049 0.99142146 0.83882997 0.25385093]
 [0.04774321 0.69330565 0.69929461 0.73605898 0.83688813]
 [0.04125596 0.79955156 0.73619953 0.15578472 0.02759906]
 [0.43499148 0.2427891  0.00132336 0.38299265 0.45880433]]
0.7360589766877078
[[0.43499148 0.2427891  0.00132336 0.38299265 0.45880433]]
[[0.25958537 0.49856049 0.99142146 0.83882997 0.25385093]
 [0.04774321 0.69330565 0.69929461 0.73605898 0.83688813]]


In [31]:
M = np.array([[1,2,3], [4,5,6], [7, 8, 9]])
vec=np.array([[1],[2],[3]])
print(M)
print(vec)
print(M**2)#multiplies each element of the matrix by itself
print(M + 2)
print(np.matmul(M,vec)) #Matrix multiplication
print(np.dot(M,M)) #Matrix multiplication
print(np.matmul(M,M))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[14]
 [32]
 [50]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [32]:
print(np.outer(vec,vec)) #Outer product
print(np.linalg.matrix_power(A,2)) #Matrix power
print(np.linalg.svd(A)) #Singular value decomposition
print(np.linalg.eigvals(A)) #Eigenvalues

[[1 2 3]
 [2 4 6]
 [3 6 9]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
SVDResult(U=array([[-0.21483724,  0.88723069,  0.40824829],
       [-0.52058739,  0.24964395, -0.81649658],
       [-0.82633754, -0.38794278,  0.40824829]]), S=array([1.68481034e+01, 1.06836951e+00, 4.41842475e-16]), Vh=array([[-0.47967118, -0.57236779, -0.66506441],
       [-0.77669099, -0.07568647,  0.62531805],
       [-0.40824829,  0.81649658, -0.40824829]]))
[ 1.61168440e+01 -1.11684397e+00 -4.22209278e-16]


## CREATING AND WRITING DATA

In [25]:
import os
path = "\\Users\\Teresa\\Desktop\\COMPU\\Clases_Filipa\\Clases_Filipa"
folder = path + "\\Data"

try:  #  This snippet of code will try to create a folder.
    os.mkdir(folder)  #  If, such a folder doesn't exist, it creates it.
except FileExistsError:  #  If it does exist, then it does nothing
    pass

In [26]:
x = np.linspace(0, 1, 11)
y = np.sin(2 * np.pi * x)

print(y)
np.save(os.path.join(folder, 'sine'), y) #  Save the array `y` in the folder `Data` with the name `sine.npy`

[ 0.00000000e+00  5.87785252e-01  9.51056516e-01  9.51056516e-01
  5.87785252e-01  1.22464680e-16 -5.87785252e-01 -9.51056516e-01
 -9.51056516e-01 -5.87785252e-01 -2.44929360e-16]
